// <auto-generated />
using System;
using E_Doctor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Doctor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117151426_AddPhysicalExamReportEntity")]
    partial class AddPhysicalExamReportEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisIllnessesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Illness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("DiagnosisIllnesses");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisSymptomsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SymptomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("DiagnosisSymptoms");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.IllnessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllnessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Illnesses");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.IllnessRuleEntity", b =>
                {
                    b.Property<int>("IllnessId")
                        .HasColumnType("int");

                    b.Property<int>("SymptomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IllnessId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("IllnessRules");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.SymptomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Common.UserActivityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientFamilyHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asthma")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancer")
                        .HasColumnType("bit");

                    b.Property<bool>("Cardiac")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("None")
                        .HasColumnType("bit");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PTB")
                        .HasColumnType("bit");

                    b.Property<int>("PatientInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientInfoId")
                        .IsUnique();

                    b.ToTable("PatientFamilyHistory");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientInformations");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientPastMedicalRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllergyToMeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asthma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diabetes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodAllergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeartProblem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hypertension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBGyneHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherIllnesses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastSurgery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientInfoId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousHospitalization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientInfoId")
                        .IsUnique();

                    b.ToTable("PatientPastMedicalRecords");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientPersonalHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlchoholBeverageDrinker")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IllicitDrugUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientInfoId")
                        .HasColumnType("int");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientInfoId")
                        .IsUnique();

                    b.ToTable("PatientPersonalHistory");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("HR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("O2Sat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysicalExams");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamFindingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbnormalFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNormal")
                        .HasColumnType("bit");

                    b.Property<string>("NormalDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalExamId")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalExamId");

                    b.HasIndex("PhysicalItemId");

                    b.ToTable("PhysicalExamFindings");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamItemsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PhysicalExamItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = false,
                            Label = "General",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Head",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Eyes",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Ears",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Nose",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Throat",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Neck",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Breast",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Chest/Lungs",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Heart",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Abdomen",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Gut",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Back",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Extremities",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Neurologic",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Skin",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2025, 11, 17, 15, 14, 25, 948, DateTimeKind.Utc).AddTicks(9593),
                            InputType = "",
                            IsActive = true,
                            Label = "Others",
                            SortOrder = 17
                        });
                });

            modelBuilder.Entity("E_Doctor.Infrastructure.Identity.AppUserIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisEntity", b =>
                {
                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisIllnessesEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Admin.DiagnosisEntity", "Diagnosis")
                        .WithMany("DiagnosIllnesses")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisSymptomsEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Admin.DiagnosisEntity", "Diagnosis")
                        .WithMany("DiagnosSymptoms")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.IllnessRuleEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Admin.IllnessEntity", "Illness")
                        .WithMany("Rules")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Doctor.Core.Domain.Entities.Admin.SymptomEntity", "Symptom")
                        .WithMany("Rules")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Illness");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientFamilyHistoryEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", "PatientInformation")
                        .WithOne("PatientFamilyHistory")
                        .HasForeignKey("E_Doctor.Core.Domain.Entities.Patient.PatientFamilyHistoryEntity", "PatientInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientInformation");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", b =>
                {
                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithOne("PatientInformation")
                        .HasForeignKey("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientPastMedicalRecordEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", "PatientInformation")
                        .WithOne("PatientPastMedicalRecord")
                        .HasForeignKey("E_Doctor.Core.Domain.Entities.Patient.PatientPastMedicalRecordEntity", "PatientInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientInformation");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientPersonalHistoryEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", "PatientInformation")
                        .WithOne("PatientPersonalHistory")
                        .HasForeignKey("E_Doctor.Core.Domain.Entities.Patient.PatientPersonalHistoryEntity", "PatientInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientInformation");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamFindingsEntity", b =>
                {
                    b.HasOne("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamEntity", "PhysicalExam")
                        .WithMany("PhysicalExamFindings")
                        .HasForeignKey("PhysicalExamId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamItemsEntity", "PhysicalExamItem")
                        .WithMany()
                        .HasForeignKey("PhysicalItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhysicalExam");

                    b.Navigation("PhysicalExamItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("E_Doctor.Infrastructure.Identity.AppUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.DiagnosisEntity", b =>
                {
                    b.Navigation("DiagnosIllnesses");

                    b.Navigation("DiagnosSymptoms");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.IllnessEntity", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Admin.SymptomEntity", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PatientInformationEntity", b =>
                {
                    b.Navigation("PatientFamilyHistory");

                    b.Navigation("PatientPastMedicalRecord");

                    b.Navigation("PatientPersonalHistory");
                });

            modelBuilder.Entity("E_Doctor.Core.Domain.Entities.Patient.PhysicalExam.PhysicalExamEntity", b =>
                {
                    b.Navigation("PhysicalExamFindings");
                });

            modelBuilder.Entity("E_Doctor.Infrastructure.Identity.AppUserIdentity", b =>
                {
                    b.Navigation("PatientInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
